#!/usr/bin/env python2.7

"""
A *BB parser that outputs a maildir.

The following license applies to this project.

Copyright (c) 2011 Etienne Millon <etienne.millon@gmail.com>
----------------------------------------------------------------------------
                       "THE BEER-WARE LICENSE"
<etienne.millon@gmail.com> wrote this file. As long as you retain this notice
you can do whatever you want with this stuff. If we meet some day, and you
think this stuff is worth it, you can buy me a beer in return.
----------------------------------------------------------------------------
"""

from mailbox import Maildir
from bb2mdir import punbb
import json
import os.path

CONF_FN = os.path.expanduser('~/.bb2mdir/bb2mdir.conf')
IDS_FN = os.path.expanduser('~/.bb2mdir/bb2mdir.ids')

def parse_json(filename):
    "Read JSON data from a file"
    json_file = open(filename)
    json_data = json.loads(json_file.read())
    json_file.close()
    assert(json_data['version'] == 1)
    return json_data

def get_config():
    "Get the application's configuration from CONF_FN"
    return parse_json(CONF_FN)

def get_ids():
    "Get the application's state from IDS_FN"
    return parse_json(IDS_FN)

def set_ids(ids):
    "Set the application's state"
    state_str = json.dumps(ids)
    state_file = open(IDS_FN, 'w')
    state_file.write(state_str)
    state_file.close()

def build_thread_handler(site, thread, maildir):
    "A factory of *BBThreads"
    assert (site['engine'] == 'punbb')
    return punbb.PunbbThread(site, thread, maildir)

def main():
    "Program entry point"

    conf = get_config()
    ids = get_ids()

    for site in conf['sites']:
        print "%s..." % site['name']
        maildir = Maildir(site['name'])
        for thread in site['threads']:
            print "  [%d]" % thread
            hdl = build_thread_handler(site, thread, maildir)
            ids['sites'][site['name']] = hdl.refresh(ids['sites'][site['name']])

    set_ids(ids)

if __name__ == "__main__":
    main()
